import mongoose from "mongoose";
import { connectToDatabase } from "../db/connection.js";
import { Event, type EventDoc } from "../models/Event.js";

type SeedEvent = Omit<EventDoc, "_id" | "createdAt" | "updatedAt">;

const OPEN_TO_ALL = "Open to All Departments";

/** The FINALIZED Porikkalam 2026 event list — transcribed verbatim from the organizing committee's brief. */
const events: SeedEvent[] = [
  {
    eventName: "SketchShift",
    slug: "sketchshift",
    category: "non-technical",
    description:
      "Participants will be given a simple sketch and must think outside the box to transform it into something unexpected and creative. The most imaginative interpretation wins.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 60,
    targetSubCategory: [],
    whyIncluded:
      "This event focuses on artistic creativity and challenges participants to think differently. It provides an engaging platform for students interested in art and creative expression.",
    teamType: "individual",
    teamSize: "Individual",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "2 Hours",
    expectedParticipants: 60,
    venue: "Drawing Hall",
    resources: "Printed A4 Sheets",
    referenceLink: null,
    budget: "₹500",
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "pen-tool",
    registrationOpen: true,
  },
  {
    eventName: "Civil CBI",
    slug: "civil-cbi",
    category: "technical",
    description:
      "Participants will be provided with images of civil engineering construction sites. They must identify defects or mistakes, determine their possible causes, and suggest practical solutions or preventive measures.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 30,
    targetSubCategory: ["Civil"],
    whyIncluded: "The event provides valuable exposure to civil engineering-related technical issues and knowledge.",
    teamType: "team",
    teamSize: "2",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "2 Hours",
    expectedParticipants: 30,
    venue: "Classroom",
    resources: "Printed A4 Sheets",
    referenceLink: null,
    budget: "₹500",
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "search",
    registrationOpen: true,
  },
  {
    eventName: "Structron",
    slug: "structron",
    category: "technical",
    description:
      "Structron is a hands-on structural engineering challenge where participants design and build a model structure using the provided materials. The structure is tested for strength, stability, and efficiency by applying an increasing load. Teams must balance design, material usage, structural integrity, and load-bearing capacity. The structure demonstrating the best overall performance will be declared the winner.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 60,
    targetSubCategory: ["Civil"],
    whyIncluded: "Promotes hands-on learning, teamwork, creativity and practical application of structural engineering concepts.",
    teamType: "team",
    teamSize: "3",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "1 Hour",
    expectedParticipants: 60,
    venue: "Classroom",
    resources: "Building materials, testing load",
    referenceLink: null,
    budget: "₹1000",
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "landmark",
    registrationOpen: true,
  },
  {
    eventName: "Deep Dive Challenge",
    slug: "deep-dive-challenge",
    category: "technical",
    description:
      "Participants will be given a subject-specific topic and must quickly understand, analyze and present it within the allotted time. The event tests technical knowledge, analytical thinking, clarity of thought, and presentation skills.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 60,
    targetSubCategory: [],
    whyIncluded: "Assesses participants' ability to learn a new concept quickly, think critically and communicate their ideas effectively.",
    teamType: "team",
    teamSize: "2",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "1 Hour",
    expectedParticipants: 60,
    venue: "Classroom",
    resources: "Projector",
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "presentation",
    registrationOpen: true,
  },
  {
    eventName: "Robo Soccer",
    slug: "robo-soccer",
    category: "technical",
    description:
      "Participants will control a robotic vehicle to play a game of soccer using skill, precision and strategy to score goals. The team that scores the highest number of goals within the allotted time will be declared the winner.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 32,
    targetSubCategory: ["Mechanical", "Production", "EEE", "EIE", "ECE"],
    whyIncluded: "An exciting audience-focused robotics event that does not require a large arena like Robo Wars.",
    teamType: "team",
    teamSize: "2",
    eventType: "competition",
    prequalifierRequired: true,
    duration: "1 Hour",
    expectedParticipants: 32,
    venue: "PJ Building",
    resources: "Soccer Field",
    referenceLink: null,
    budget: "₹1000",
    prizePool: null,
    registrationFee: null,
    poster: "/events/robo-soccer.jpeg",
    icon: "bot",
    registrationOpen: true,
  },
  {
    eventName: "Flightcraft, Skyworks",
    slug: "flightcraft-skyworks",
    category: "technical",
    description:
      "Participants will build a paper glider using only the materials provided by the organizers within the allotted time. The glider will then be launched to achieve maximum flight time through effective design, balance, stability, and aerodynamics. The participant/team whose glider remains airborne for the longest duration will be declared the winner.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 60,
    targetSubCategory: ["Mechanical", "Production", "EEE", "EIE", "ECE"],
    whyIncluded:
      "Encourages participants to optimize designs using principles of aerodynamics while remaining accessible to students from different disciplines.",
    teamType: "team",
    teamSize: "2",
    eventType: "competition",
    prequalifierRequired: true,
    duration: "2 Hours",
    expectedParticipants: 60,
    venue: "Alumni Auditorium",
    resources: null,
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "plane",
    registrationOpen: true,
  },
  {
    eventName: "Water Rocketry",
    slug: "water-rocketry",
    category: "technical",
    description:
      "Water rocketry is a nostalgic event performed at a higher level for a more dramatic effect. Evaluation is based on flight distance and travel mode.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 60,
    targetSubCategory: ["Mechanical", "Production", "Automobile"],
    whyIncluded:
      "Water rocketry provides an exciting rocket-launch experience while being safer than conventional rocket launches and capable of attracting more participants.",
    teamType: "team",
    teamSize: "2",
    eventType: "competition",
    prequalifierRequired: true,
    duration: "1 Hour",
    expectedParticipants: 60,
    venue: "Open Ground",
    resources: "Launcher",
    referenceLink: null,
    budget: "₹1500",
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "rocket",
    registrationOpen: true,
  },
  {
    eventName: "What If? (Reverse Engineering & Debugging)",
    slug: "what-if-reverse-engineering-debugging",
    category: "technical",
    description:
      "Explore what happens when electrical circuits are connected incorrectly. Participants must analyze faults, predict circuit behavior, identify the cause, suggest the correct solution, and troubleshoot real-world scenarios. The event tests troubleshooting, analytical thinking and electrical safety knowledge.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 60,
    targetSubCategory: ["EEE", "ECE", "EIE"],
    whyIncluded: "Develops practical troubleshooting skills, strengthens understanding of electrical concepts and improves safety awareness.",
    teamType: "team",
    teamSize: "Team",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "30 Minutes",
    expectedParticipants: 60,
    venue: "Classrooms",
    resources: "Electrical Components",
    referenceLink: null,
    budget: "₹3000",
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "circuit-board",
    registrationOpen: true,
  },
  {
    eventName: "Robo Rally",
    slug: "robo-rally",
    category: "technical",
    description:
      "Participants are required to design and build their own robotic vehicle to navigate a specially designed obstacle track. Multiple checkpoints will be placed along the course. If a robot deviates from the track, overturns, or cannot proceed due to an obstacle, it will be repositioned at the last successfully crossed checkpoint and the run will resume with the prescribed time penalty. Only robots complying with the specified design and technical regulations will be allowed to participate — robots failing inspection will be disqualified before the competition begins.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 40,
    targetSubCategory: ["Mechanical", "Production", "EEE", "EIE", "ECE"],
    whyIncluded:
      "Combines design, fabrication, programming, electronics, and problem-solving. It provides a hands-on engineering challenge around mobility and navigation.",
    teamType: "team",
    teamSize: "Team",
    eventType: "competition",
    prequalifierRequired: true,
    duration: "Half Day",
    expectedParticipants: 40,
    venue: "PJ Building",
    resources: "Obstacle Course",
    referenceLink: null,
    budget: "₹3000",
    prizePool: null,
    registrationFee: null,
    poster: "/events/robo-rally.jpeg",
    icon: "bot",
    registrationOpen: true,
  },
  {
    eventName: "Code Detective – Speed Relay",
    slug: "code-detective-speed-relay",
    category: "technical",
    description:
      "A four-member coding relay. Round 1 — Bug Fix (5 minutes): Member 1 fixes as many bugs as possible before the code is locked and passed to Member 2. Round 2 — Optimize (5 minutes): Member 2 reduces time complexity and memory usage without starting from scratch. Round 3 — Test (5 minutes): Member 3 runs hidden test cases and fixes edge cases and runtime errors. Round 4 — Explain (5–10 minutes): Member 4 explains what bugs were fixed, why the solution is faster, its time complexity, and memory optimization. Teams finishing before the timer may earn bonus points or receive a harder optimization challenge for extra marks. The organizer may adjust the time allocated for each round.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 60,
    targetSubCategory: ["CSE", "IT", "AIML", "AIDS"],
    whyIncluded:
      "The event rewards speed, teamwork and coding quality rather than simply producing a working solution. It simulates how developers work under time pressure in real companies.",
    teamType: "team",
    teamSize: "4",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "1 Hour",
    expectedParticipants: 60,
    venue: "DCKAP Room",
    resources: "Power source and Wi-Fi",
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "bug",
    registrationOpen: true,
  },
  {
    eventName: "Human Matrix",
    slug: "human-matrix",
    category: "non-technical",
    description:
      "A treasure-hunt style team event where participants follow a series of clues, riddles and challenges hidden across the campus. Each solved clue leads the team closer to the final treasure. The fastest team to complete the hunt wins.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 44,
    targetSubCategory: [],
    whyIncluded:
      "Promotes teamwork, communication, observation, creativity and quick thinking. It requires no technical knowledge and is engaging for students from all departments.",
    teamType: "team",
    teamSize: "4",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "2 Hours",
    expectedParticipants: 44,
    venue: "Open Area",
    resources: null,
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "clipboard-list",
    registrationOpen: true,
  },
  {
    eventName: "Hackathon",
    slug: "hackathon",
    category: "technical",
    description:
      "A team-based competition where participants solve real-world or problem-based challenges by developing software solutions within a fixed time. Teams brainstorm, code, test and present their solutions. The best-performing solution emerges as the winner.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 30,
    targetSubCategory: ["CSE", "IT", "AIML", "AIDS"],
    whyIncluded:
      "Develops coding skills, logical thinking, problem-solving, teamwork and time management. It gives participants an opportunity to apply programming knowledge to practical challenges and build innovative software solutions.",
    teamType: "team",
    teamSize: "Team",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "6 Hours",
    expectedParticipants: 30,
    venue: "DCKAP Room",
    resources: "Power source and Wi-Fi",
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "brain-circuit",
    registrationOpen: true,
  },
  {
    eventName: "IPL Auction",
    slug: "ipl-auction",
    category: "non-technical",
    description:
      "A fun strategy-based event where participants form teams and compete to build their ideal cricket squad through a simulated IPL-style auction. Participants must bid for players, manage their budget, make strategic decisions, and create a balanced and competitive team.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 44,
    targetSubCategory: [],
    whyIncluded: "Combines cricket knowledge, strategy, decision-making, negotiation and financial management.",
    teamType: "team",
    teamSize: "Team",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "2 Hours",
    expectedParticipants: 44,
    venue: "Classroom",
    resources: null,
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "message-square-text",
    registrationOpen: true,
  },
  {
    eventName: "Paper Presentation",
    slug: "paper-presentation",
    category: "technical",
    description:
      "A platform where participants present research, ideas, innovations or technical concepts on a chosen topic before a panel of judges. Participants are evaluated based on content, clarity, presentation skills, and ability to answer questions.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 100,
    targetSubCategory: [],
    whyIncluded:
      "Develops research, communication, presentation, critical thinking and technical knowledge. It provides students an opportunity to showcase ideas and gain experience presenting them professionally.",
    teamType: "team",
    teamSize: "Team",
    eventType: "competition",
    prequalifierRequired: true,
    duration: "6 Hours",
    expectedParticipants: 100,
    venue: "Classroom",
    resources: "Projector",
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "presentation",
    registrationOpen: true,
  },
  {
    eventName: "Poster Designing",
    slug: "poster-designing",
    category: "non-technical",
    description:
      "Participants design an attractive and impactful poster based on a given theme or topic within a specified time, using creativity, artistic expression, visual communication and innovative thinking.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 40,
    targetSubCategory: [],
    whyIncluded:
      "Encourages creativity, artistic expression, visual communication and innovative thinking. It requires minimal resources and provides students an opportunity to showcase their design skills.",
    teamType: "individual",
    teamSize: "Individual",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "1 Hour",
    expectedParticipants: 40,
    venue: "Classroom",
    resources: null,
    referenceLink: null,
    budget: "₹780",
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "pen-tool",
    registrationOpen: true,
  },
  {
    eventName: "The Outliner",
    slug: "the-outliner",
    category: "non-technical",
    description:
      "Participants are given a specific sketch and must think outside the box to draw what isn't intended in the given sketch — testing imagination and artistic interpretation.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 60,
    targetSubCategory: [],
    whyIncluded:
      "A dedicated art-focused event that challenges participants to think differently — an engaging, accessible addition to the Mega Event.",
    teamType: "individual",
    teamSize: "Individual",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "2 Hours",
    expectedParticipants: 60,
    venue: "Classroom",
    resources: "Printed A4 sheets",
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "pen-tool",
    registrationOpen: true,
  },
  {
    eventName: "SiteSprint",
    slug: "sitesprint",
    category: "technical",
    description:
      "A real-world construction management challenge where teams act as site engineers and solve practical problems such as budget constraints, material shortages, safety issues, and design changes.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 40,
    targetSubCategory: ["Civil"],
    whyIncluded:
      "Unlike quiz-style engineering competitions, it simulates the work of a real site engineer. It tests planning, leadership, technical knowledge, and the ability to make decisions under pressure. It's easy to organize, industry-relevant, and gives participants a realistic Civil Engineering experience.",
    teamType: "team",
    teamSize: "Team",
    eventType: "competition",
    prequalifierRequired: true,
    duration: "To be announced",
    expectedParticipants: 40,
    venue: "Classroom",
    resources: null,
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "hard-hat",
    registrationOpen: true,
  },
  {
    eventName: "Concept Clash",
    slug: "concept-clash",
    category: "technical",
    description:
      "Concept Clash is a technical debate competition where two teams compete by presenting opposing perspectives on a given topic. Each pair of teams is assigned the same topic, with one team defending the concept (Pro) and the other challenging it (Con). Teams must support their arguments with technical knowledge, logical reasoning, practical examples, and effective rebuttals. The team that demonstrates the strongest technical understanding, critical thinking, and overall debate performance will be declared the winner.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 60,
    targetSubCategory: [],
    whyIncluded:
      "Concept Clash promotes technical thinking, communication, and critical analysis of engineering concepts. By encouraging participants to defend and challenge ideas, it creates an engaging platform for knowledge-sharing, teamwork, and healthy competition — a valuable addition to the Mega Event.",
    teamType: "team",
    teamSize: "Team",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "1 Hour",
    expectedParticipants: 60,
    venue: "Classroom",
    resources: null,
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "message-square-text",
    registrationOpen: true,
  },
  {
    eventName: "Brainstorm Battle",
    slug: "brainstorm-battle",
    category: "technical",
    description:
      "A three-round technical event. Round 1 — Qualifier: an aptitude round. Round 2 — Group Discussion: participants discuss a technical topic to assess communication, teamwork, and analytical skills. Round 3 — Final: a one-on-one interview.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 60,
    targetSubCategory: [],
    whyIncluded:
      "Assesses candidates through a structured aptitude, group discussion, and interview format — mirroring real recruitment processes and building employability skills.",
    teamType: "individual",
    teamSize: "Individual",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "1 Hour",
    expectedParticipants: 60,
    venue: "Classroom",
    resources: null,
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "brain-cog",
    registrationOpen: true,
  },
  {
    eventName: "Gear Heads",
    slug: "gear-heads",
    category: "technical",
    description:
      "A multi-round technical event testing automotive expertise. Round 1 is a written quiz covering internal combustion engines, modern automotive technologies, and components. Round 2 puts short-listed participants through hands-on challenges such as a mechanical assembly/disassembly task or a troubleshooting simulation, all under a fixed time limit.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 40,
    targetSubCategory: ["Mechanical", "Production", "Automobile"],
    whyIncluded:
      "Bridges the gap between theoretical knowledge and practical application, specifically catering to core engineering competencies. It promotes healthy competition among students, working under pressure, and enhances core technical engagement within the symposium.",
    teamType: "team",
    teamSize: "Team",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "Half Day",
    expectedParticipants: 40,
    venue: "Seminar Hall / Machine Shop",
    resources: null,
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "cog",
    registrationOpen: true,
  },
  {
    eventName: "Industry 5.0 Challenge",
    slug: "industry-50-challenge",
    category: "technical",
    description:
      "Instead of a paper presentation, teams get 2 to 3 hours to prepare a solution to a real industry problem and pitch it Shark Tank–style.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 40,
    targetSubCategory: [],
    whyIncluded:
      "Providing real-time industry problems helps us evaluate how quickly teams respond and how effectively they handle critical situations — a skill valuable in real-life scenarios as well.",
    teamType: "team",
    teamSize: "Team",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "2 Hours",
    expectedParticipants: 40,
    venue: "Classroom",
    resources: "Projector, internet",
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "expo",
    registrationOpen: true,
  },
  {
    eventName: "Product Presentation",
    slug: "product-presentation",
    category: "technical",
    description:
      "A Product Presentation event where participants showcase a fully functional product that solves a real-world problem. The product should be complete and demonstrate its readiness for practical use or further commercialization. Participants explain the design process, working principle, technical implementation, testing results, and applications while demonstrating the product live to the judges.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 40,
    targetSubCategory: [],
    whyIncluded:
      "Encourages students to transform innovative ideas into fully functional products by integrating technology and testing real-world solutions. It enhances technical knowledge, problem-solving, teamwork, and presentation skills, and provides a platform for participants to showcase practical engineering solutions with real-world impact.",
    teamType: "team",
    teamSize: "Team",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "Full Day",
    expectedParticipants: 40,
    venue: "Showcase area (tables and chairs provided)",
    resources: "Table and chair, showcase space with extensions",
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "presentation",
    registrationOpen: true,
  },
  {
    eventName: "Requirement Rumble",
    slug: "requirement-rumble",
    category: "technical",
    description:
      "Requirement Rumble simulates a real-world software development process where participants transform client requirements into a working solution. Round 1 — Client Chaos: teams interact with judges acting as clients to gather and clarify requirements. Round 2 — Blueprint Builder: teams convert the gathered requirements into user stories, a business requirements document, and simple design artifacts such as wireframes or flow diagrams. Round 3 — Build Sprint: teams develop a working prototype based on their blueprint and modify it to accommodate a new requirement introduced mid-development.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 40,
    targetSubCategory: [],
    whyIncluded:
      "Bridges the gap between requirement engineering and hands-on software development, giving participants an industry-realistic view of the full software development lifecycle — going beyond traditional coding competitions.",
    teamType: "team",
    teamSize: "Team",
    eventType: "competition",
    prequalifierRequired: false,
    duration: "2 Hours",
    expectedParticipants: 40,
    venue: "Lab",
    resources: "Lab and computers",
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "circuit-board",
    registrationOpen: true,
  },
  {
    eventName: "AI Workshop",
    slug: "ai-workshop",
    category: "workshop",
    description:
      "A hands-on workshop on working with AI in the current era, and why not using it is a costly mistake. The traditional idea of ChatGPT and Gemini being the only AI tools worth knowing is outdated — participants are introduced to other important AI tools engineers and students should know about.",
    eligibility: OPEN_TO_ALL,
    targetParticipants: 100,
    targetSubCategory: [],
    whyIncluded:
      "AI is a major breakthrough of this era, and students and engineers need to know how to work with it. This workshop gives everyone a practical introduction to AI tools beyond the obvious ones, and why their career depends on knowing them.",
    teamType: "individual",
    teamSize: "Individual",
    eventType: "participation",
    prequalifierRequired: false,
    duration: "2 Hours",
    expectedParticipants: 100,
    venue: "Seminar Hall",
    resources: null,
    referenceLink: null,
    budget: null,
    prizePool: null,
    registrationFee: null,
    poster: null,
    icon: "brain-circuit",
    registrationOpen: true,
  },
];

async function seed(): Promise<void> {
  await connectToDatabase();

  const slugs = events.map((e) => e.slug);
  const removed = await Event.deleteMany({ slug: { $nin: slugs } });
  if (removed.deletedCount) {
    console.log(`[seed:events] removed ${removed.deletedCount} event(s) no longer in the finalized list`);
  }

  for (const event of events) {
    await Event.updateOne({ slug: event.slug }, { $set: event }, { upsert: true });
    console.log(`[seed:events] upserted ${event.slug}`);
  }

  console.log(`[seed:events] done — ${events.length} finalized events in the database`);
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((error) => {
  console.error("[seed:events] failed:", error);
  process.exit(1);
});
